### ISSUE TITLE
Support pager

### ISSUE THREAD

**Issue by cxw42** [skaji/perl-tldr#1]
Thank you for this tool!  Would you be willing to add an option for it to pipe output to less or another pager (IO::Pager?), or use a pager (Term::Pager?) internally?  Thanks for considering this request!

**Comment by skaji** [comment]
Thanks. I will work on it.

**Comment by skaji** [comment]
@cxw42 Could you try #2 ?

**Comment by skaji** [comment]
Released a new version https://metacpan.org/release/SKAJI/App-tldr-0.10
