### ISSUE TITLE
Option to downgrade Unicode characters to ASCII for terminals/environments that don't support Unicode

### ISSUE THREAD

**Issue by esabol** [skaji/perl-tldr#4]
My terminal and/or the font my terminal uses and/or my pager and/or my environment variables don't support displaying the Unicode characters (the checkmark and the sushi emoji) commonly found in the `tldr` output.

Would you consider adding a command line option to downgrade these Unicode characters to ASCII (say an asterisk and a dollar sign, respectively)?

Or somehow detecting whether the terminal can display such characters (possibly by looking at $ENV{LANG} or the output of the `stty` command) and then downgrading those Unicode characters to ASCII automagically?

Thanks!

**Comment by skaji** [comment]
@esabol Thank you for bringing this up.
Can you take a look at #6 ?

**Comment by skaji** [comment]
Released a new version to CPAN https://metacpan.org/release/SKAJI/App-tldr-0.11
